# Use Kali base image
FROM kalilinux/kali-rolling

# Update and upgrade the system
RUN apt update && apt upgrade -y

# Install the necessary packages
RUN apt install -y \
    procps \
    net-tools \
    iproute2 \
    golang \
    sudo

#Install tools from apt
RUN apt install -y \
    nikto \
    nmap \
    gobuster \
    dirbuster \
    metasploit-framework \
    subfinder \
    amass \
    whatweb \
    sqlmap \
    seclists \
    wordlists \
    nuclei \
    getallurls \
    waybackpy \
    wafw00f

#Install golang tools
RUN go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest && \
    go install github.com/tomnomnom/waybackurls@latest && \
    go install github.com/lc/gau/v2/cmd/gau@latest && \
    go install github.com/projectdiscovery/katana/cmd/katana@latest && \
    go install github.com/hahwul/dalfox/v2@latest && \
    cp ~/go/bin/httpx /usr/bin && \
    cp ~/go/bin/waybackurls /usr/bin && \
    cp ~/go/bin/gau /usr/bin && \
    cp ~/go/bin/gf /usr/bin && \
    cp ~/go/bin/katana /usr/bin && \
    cp ~/go/bin/dalfox /usr/bin

# Set the default command
CMD ["bash"]